[package]
name    = "typed-ipv4-echo"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.184"

[lints.clippy]
all      = { level = "warn", priority = -1 }
nursery  = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

allow_attributes                = "forbid"
allow_attributes_without_reason = "forbid"
expect_used                     = "forbid"
unwrap_used                     = "forbid"

[lints.rust]
unsafe_code = "deny"
