words = [
    "CWR",
    "DSCP",
    "ECE",
    "IFNAMSIZ",
    "IHL",
    "ISN",
    "MTU",
    "NUL",
    "POLLIN",
    "PSH",
    "Swatinem",
    "TUNSETIFF",
    "UDP",
    "URG",
    "acked",
    "acking",
    "acks",
    "clippy",
    "datagrams",
    "dtolnay",
    "ifr",
    "ifreq",
    "ipv",
    "lookups",
    "netcat",
    "nxt",
    "oldact",
    "pfd",
    "pollfd",
    "rcv",
    "resends",
    "revents",
    "rto",
    "rustfmt",
    "sigaction",
    "sigemptyset",
    "signedness",
    "signum",
    "sigset",
    "snd",
    "subslice",
    "syscall",
    "unacked",
    "userspace",
    "vtable",
    "xzf",
]
ignore_paths = ["Cargo.lock"]
ignore_patterns = [
    '\b[a-fA-F0-9]{64}\b',
    '\b0x[a-fA-F0-9_]{4,9}\b',
]
