edition = "2024" # Explicit edition in case rustfmt is run directly

chain_width          = 60      # Set back to default to override `use_small_heuristics`
comment_width        = 100
fn_single_line       = true
format_strings       = true
group_imports        = "One"
hex_literal_case     = "Upper"
imports_granularity  = "One"
use_small_heuristics = "Max"
wrap_comments        = true
